name: dart_hydrologis_utils
description: Common dart utilities lib for our projects.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # BSD
  # timezone: ^0.5.7
  # BSD
  intl: ">=0.16.1 <=0.17.0"
  # Apache 2.0
  image: ^3.0.2
  path: ^1.8.0

  # MIT
  # xml: ">=4.3.0 <=5.1.2"
  xml: 5.3.1

dev_dependencies:
  test: ^1.6.0
